#!/bin/sh

set -e

readonly VERSION=0.1.0
readonly JAR_FILE="cyanite-fetcher-$VERSION-standalone.jar"
readonly JAVA_CMD="java -Xms1024M -Xmx8192M -Xmn800M -jar"

readonly SCRIPT_DIR=$(dirname $0)
readonly NEAR_FILE=$SCRIPT_DIR/$JAR_FILE
readonly UBERJAR_FILE=$SCRIPT_DIR/target/uberjar/$JAR_FILE

if [ -f $NEAR_FILE ]; then
	$JAVA_CMD $NEAR_FILE $*
elif [ -f $UBERJAR_FILE ]; then
	$JAVA_CMD $UBERJAR_FILE $*
else
	echo "File '$JAR_FILE' not found!"
	exit 1
fi
